
export default async function handler(req, res) {
  const { imageUrl, prompt } = req.body;

  try {
    const shopifyProduct = {
      product: {
        title: `Custom AI Shirt - ${prompt}`,
        body_html: `<strong>Generated by AI</strong>`,
        vendor: "AI Store",
        product_type: "T-shirt",
        images: [{ src: imageUrl }],
        variants: [{ option1: "Default", price: "25.00", sku: `AI-${Date.now()}` }],
        options: [{ name: "Title", values: ["Default"] }]
      }
    };

    const shopifyRes = await fetch(`https://${process.env.SHOPIFY_DOMAIN}/admin/api/2023-04/products.json`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Shopify-Access-Token': process.env.SHOPIFY_ADMIN_TOKEN,
      },
      body: JSON.stringify(shopifyProduct),
    });

    if (!shopifyRes.ok) throw new Error('Failed to create product');
    res.status(200).json({ success: true });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to create product' });
  }
}
